export const TARGET_ROLE_OPTIONS = [
  "Account Executive",
  "Administrative Assistant",
  "AI Engineer",
  "Android Developer",
  "Backend Developer",
  "Brand Strategist",
  "Business Analyst",
  "Business Development",
  "Cloud Engineer",
  "Content Creator",
  "Content Strategist",
  "Copywriter",
  "Customer Success Specialist",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Data Engineer",
  "Data Scientist",
  "Database Administrator",
  "DevOps Engineer",
  "Digital Marketing Specialist",
  "Finance Analyst",
  "Frontend Developer",
  "Full Stack Developer",
  "Graphic Designer",
  "HR Generalist",
  "iOS Developer",
  "IT Support Specialist",
  "Machine Learning Engineer",
  "Marketing Associate",
  "Marketing Specialist",
  "Mobile Developer",
  "Operations Specialist",
  "Product Analyst",
  "Product Designer",
  "Product Manager",
  "Project Manager",
  "QA Engineer",
  "Recruiter",
  "Sales Development Representative",
  "Scrum Master",
  "SEO Specialist",
  "Social Media Specialist",
  "Software Engineer",
  "System Analyst",
  "Technical Writer",
  "UI Designer",
  "UI/UX Designer",
  "UX Researcher",
  "Visual Designer",
] as const;

export const SUGGESTED_TARGET_ROLES = [
  "Software Engineer",
  "Product Manager",
  "Data Analyst",
  "UI/UX Designer",
  "Visual Designer",
  "Marketing Specialist",
] as const;
